name: example
description: Example of apsl_ads_flutter
publish_to: "none"
version: 1.2.15

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  apsl_ads_flutter:
    path: ../
  flutter:
    sdk: flutter
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
