name: apsl_ads_flutter
description: Apsl Ads is a wrapper around famous ad packages which let you
  integrate ads easily
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  applovin_max: ^2.6.0
  collection: ^1.17.0
  easy_audience_network: ^0.0.6
  flutter:
    sdk: flutter
  google_mobile_ads: ^3.0.0
  logger: ^1.3.0
  unity_ads_plugin: ^0.3.8

dev_dependencies:
  flutter_lints: ^2.0.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
