name: apsl_ads_flutter
description: Apsl Ads is a wrapper around famous ad packages which let you
  integrate ads easily
version: 1.2.8
homepage: https://github.com/appstonelabgit/apsl_ads_flutter
repository: https://github.com/appstonelabgit/apsl_ads_flutter

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: 
  easy_audience_network: ^0.0.7
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.2.0
  logger: ^2.4.0
  unity_ads_plugin: ^0.3.21

dev_dependencies:
  flutter_lints: ^5.0.0

flutter: null
